# Generated by Django 5.1.1 on 2025-06-04 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('siglas', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'ordering': ['universidad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('siglas', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Universidad',
                'verbose_name_plural': 'Universidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagado', 'Pagado y en revisión'), ('confirmado', 'Pago confirmado'), ('rechazado', 'Pago rechazado'), ('cancelado', 'Compra cancelada')], default='pendiente', max_length=20)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('codigo_seguimiento', models.CharField(max_length=50, null=True, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='DameDoy.facultad')),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='DameDoy.universidad')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['universidad', 'facultad', 'nombre'],
                'unique_together': {('universidad', 'facultad', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=20)),
                ('semestre', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='DameDoy.carrera')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='DameDoy.facultad')),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='DameDoy.universidad')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['universidad', 'facultad', 'carrera', 'semestre', 'nombre'],
                'unique_together': {('universidad', 'facultad', 'carrera', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='DameDoy.carrera')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='DameDoy.facultad')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='DameDoy.materia')),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='DameDoy.universidad')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['universidad', 'facultad', 'carrera', 'materia', 'apellido', 'nombre'],
                'unique_together': {('universidad', 'facultad', 'carrera', 'materia', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título')),
                ('tipo', models.CharField(blank=True, choices=[('apunte', 'Apunte'), ('examen', 'Examen'), ('proyecto', 'Proyecto'), ('libro', 'Libro'), ('otros', 'Otros')], max_length=50, null=True, verbose_name='Tipo de Material')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicación')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='materiales/', verbose_name='Imagen (opcional)')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente de revisión'), ('publicado', 'Publicado'), ('rechazado', 'Rechazado'), ('archivado', 'Archivado'), ('eliminado', 'Eliminado'), ('suspendido', 'Suspendido'), ('vendido', 'Vendido/No disponible')], default='borrador', max_length=20, verbose_name='Estado')),
                ('motivo_rechazo', models.TextField(blank=True, null=True, verbose_name='Motivo de rechazo')),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('carrera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DameDoy.carrera')),
                ('docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DameDoy.docente')),
                ('facultad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DameDoy.facultad')),
                ('materia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DameDoy.materia')),
                ('universidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DameDoy.universidad')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DameDoy.compra')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DameDoy.material')),
            ],
            options={
                'ordering': ['-fecha_agregado'],
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='materiales',
            field=models.ManyToManyField(through='DameDoy.DetalleCompra', to='DameDoy.material'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pago_recibido', 'Pago Recibido'), ('pago_confirmado', 'Pago Confirmado'), ('pago_rechazado', 'Pago Rechazado'), ('compra_realizada', 'Compra Realizada'), ('material_vendido', 'Material Vendido'), ('material_publicado', 'Material Publicado'), ('material_rechazado', 'Material Rechazado')], max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('referencia_id', models.IntegerField(blank=True, null=True)),
                ('referencia_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_portada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('redes_sociales', models.JSONField(blank=True, default=dict)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('qr_pago', models.ImageField(blank=True, null=True, upload_to='qr_pagos/', verbose_name='QR para pagos')),
                ('cuenta_banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de cuenta bancaria')),
                ('banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del banco')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.AddField(
            model_name='facultad',
            name='universidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facultades', to='DameDoy.universidad'),
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DameDoy.material')),
            ],
            options={
                'ordering': ['-fecha_agregado'],
                'unique_together': {('usuario', 'material')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='facultad',
            unique_together={('universidad', 'siglas')},
        ),
    ]
