# Generated by Django 5.1.1 on 2025-05-27 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DameDoy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
        migrations.RemoveField(
            model_name='material',
            name='categoria',
        ),
        migrations.AddField(
            model_name='material',
            name='carrera',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Carrera'),
        ),
        migrations.AddField(
            model_name='material',
            name='docente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Docente'),
        ),
        migrations.AddField(
            model_name='material',
            name='facultad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Facultad'),
        ),
        migrations.AddField(
            model_name='material',
            name='materia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Materia'),
        ),
        migrations.AddField(
            model_name='material',
            name='tipo',
            field=models.CharField(blank=True, choices=[('apunte', 'Apunte'), ('examen', 'Examen'), ('proyecto', 'Proyecto'), ('libro', 'Libro'), ('otros', 'Otros')], max_length=50, null=True, verbose_name='Tipo de Material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='material',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='material',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicación'),
        ),
        migrations.AlterField(
            model_name='material',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='materiales/', verbose_name='Imagen (opcional)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='material',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título'),
        ),
    ]
