# Generated by Django 5.1.1 on 2025-06-04 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DameDoy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docente',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Docente', 'verbose_name_plural': 'Docentes'},
        ),
        migrations.AlterField(
            model_name='docente',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DameDoy.carrera'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DameDoy.facultad'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DameDoy.materia'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='universidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DameDoy.universidad'),
        ),
    ]
