# Generated by Django 5.1.1 on 2025-06-05 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DameDoy', '0002_alter_docente_options_alter_docente_carrera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos_materiales/')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('tipo_archivo', models.CharField(default='otro', max_length=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='DameDoy.material')),
            ],
            options={
                'verbose_name': 'Archivo de Material',
                'verbose_name_plural': 'Archivos de Material',
            },
        ),
    ]
