# Generated by Django 5.1.1 on 2025-06-05 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DameDoy', '0003_archivomaterial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchivoMaterial',
        ),
    ]
