# Generated by Django 5.1.1 on 2025-05-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DameDoy', '0003_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='foto_portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
