# Generated by Django 5.1.1 on 2025-05-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DameDoy', '0004_perfilusuario_foto_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente de revisión'), ('publicado', 'Publicado'), ('rechazado', 'Rechazado'), ('archivado', 'Archivado'), ('eliminado', 'Eliminado'), ('suspendido', 'Suspendido'), ('vendido', 'Vendido/No disponible')], default='borrador', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='material',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
        migrations.AddField(
            model_name='material',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de rechazo'),
        ),
    ]
