# Generated by Django 5.1.1 on 2025-06-05 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DameDoy', '0004_delete_archivomaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos_materiales/', verbose_name='Archivo')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_archivo', models.CharField(max_length=20)),
                ('tamanio', models.IntegerField(verbose_name='Tamaño en bytes')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='DameDoy.material')),
            ],
            options={
                'verbose_name': 'Archivo de Material',
                'verbose_name_plural': 'Archivos de Material',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
