# Generated by Django 5.1.1 on 2025-05-31 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DameDoy', '0005_material_estado_material_fecha_ultima_modificacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagado', 'Pagado'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('materiales', models.ManyToManyField(to='DameDoy.material')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DameDoy.material')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_agregado'],
                'unique_together': {('usuario', 'material')},
            },
        ),
    ]
