# Generated by Django 5.1.1 on 2025-05-31 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DameDoy', '0006_compra_carritoitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
