# Generated by Django 5.1.1 on 2025-05-31 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DameDoy', '0007_delete_compra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagado', 'Pagado y en revisión'), ('confirmado', 'Pago confirmado'), ('rechazado', 'Pago rechazado'), ('cancelado', 'Compra cancelada')], default='pendiente', max_length=20)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('codigo_seguimiento', models.CharField(max_length=50, null=True, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DameDoy.compra')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DameDoy.material')),
            ],
            options={
                'ordering': ['-fecha_agregado'],
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='materiales',
            field=models.ManyToManyField(through='DameDoy.DetalleCompra', to='DameDoy.material'),
        ),
    ]
