# Generated by Django 5.1.1 on 2025-05-31 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DameDoy', '0008_compra_detallecompra_compra_materiales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pago_recibido', 'Pago Recibido'), ('pago_confirmado', 'Pago Confirmado'), ('pago_rechazado', 'Pago Rechazado'), ('compra_realizada', 'Compra Realizada'), ('material_vendido', 'Material Vendido'), ('material_publicado', 'Material Publicado'), ('material_rechazado', 'Material Rechazado')], max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('referencia_id', models.IntegerField(blank=True, null=True)),
                ('referencia_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
