# Generated by Django 5.1.1 on 2025-06-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DameDoy', '0009_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del banco'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='cuenta_banco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de cuenta bancaria'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='qr_pago',
            field=models.ImageField(blank=True, null=True, upload_to='qr_pagos/', verbose_name='QR para pagos'),
        ),
    ]
